packages:
  - app-vite
  - app-webpack
  - vite-plugin
  - vite-plugin/playground
  - extras
  - ui
  - ui/playground
  - ui/testing
  - create-quasar
  - cli
  - docs

  - utils/render-ssr-error
  - utils/ssl-certificate
  - utils/eslint-config

  - playground/app-vite-ts

  # The packages below are not included. Use their individual folders.
  # - icongenie
  # - utils/babel-preset-app
  # - utils/ssr-helpers

catalog:
  eslint: ^9.23.0
